### ISSUE TITLE
Should blocked users be able to see people who have blocked them?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-friends#12]
Current scenario:

- Alice follows Bob
- Bob blocks Alice
- Alice can see the block
- Alice continues to receive Bob's new messages

Is this the intended behavior, or is this indicative of a bug? I was under the impression that nobody should replicate Alice's feed to Bob, since she blocked him, but it looks like this may not be the case.

See: `%SqG1B4/UabucCy7v2zrI7JAkDy/dh/qwNa/F92sNFIc=.sha256`

**Comment by christianbundy** [comment]
Is that an ssb-friends thing, or maybe ssb-ebt? I'd be interested in testing this although I'm not sure how to determine when a pub is replicating a message from someone who has blocked me.

**Comment by dominictarr** [comment]
ssb-friends is the source for knowing the current state, but ssb-ebt and scuttlebot/plugins/replication/legacy.js are the things actually responsible for implementing that behaviour. There is test coverage for this in scuttlebot too, which now uses ssb-ebt by default.

**Comment by dominictarr** [comment]
@christianbundy in ebt, you could test it by connecting to a pub and faking ebt - connect to a pub, call ebt.replicate() then send `{<blockingFeed>: 0}` (meaning, "I want <blockingFeed>") if they are correctly respecting the block, they should send back -1, to pretend they arn't interested in that feed (note: they'll also do this if they just don't care about that feed, which is part of the point, you shouldn't be able to tell they have blocked you) if they send back something else, then that is wrong.
