### ISSUE TITLE
Tests stall

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-friends#29]
When I run the test they get caught at "cleanup" test steps which are supposed to close the sbot.

The tests don't progress past the text and the test suite can't error or exit

**Comment by dominictarr** [comment]
attempting to reproduce this. so for it's ending fine here.
that suggests to me there is a deeper problem

**Comment by dominictarr** [comment]
I reinstalled the latest deps and it still closes for me. hmm.

**Comment by christianbundy** [comment]
Oops, I should have made [this comment](https://github.com/ssbc/ssb-friends/pull/30#issuecomment-460064926) here instead.

**Comment by Powersource** [comment]
from reading the closed pr this sounds resolved
