### ISSUE TITLE
hops shouldn't be counting blocks

### ISSUE THREAD

**Issue by mmckegg** [ssbc/ssb-friends#3]
Right now if I ask for the `hops` between myself and someone that I block, I get `1` implying that I follow them. 

Probably it should ignore the blocks and then just use whatever value it would have if you didn't follow the person.

/cc @dominictarr @ahdinosaur @clehner

**Comment by mmckegg** [comment]
It also seems to be including people that you have unfollowed in the traversal.

**Comment by dominictarr** [comment]
what are you using this for?
hops is currently commented as "legacy, debugging"
https://github.com/ssbc/ssb-friends/blob/master/index.js#L189-L190

**Comment by mmckegg** [comment]
@dominictarr 

Ah, that explains a lot. Missed that comment. Also I didn't know at the time that you could just get this info from `createFriendStream` with `{meta: true}`

I was using it for something experimental in patchwork, but stopped because it was buggy.

Consider this unimportant now! Go ahead and close if you want.
