### ISSUE TITLE
alternate ssb-friends approach

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-friends#32]
Way back ages ago, we noticed that onboarding was taking way too long. @mmckegg and I managed to track it down to ssb-friends blocking the cpu! [that was in oct 2017](https://github.com/ssbc/ssb-friends/commit/c9099afa03dea7608c2fc0c1559a85eb832c6714) I was quite surprised that this was the bottleneck but it was causing a significant slow down.

There were two basic approaches I considered
1. don't retraverse graph on every update - debounce it, and reupdate occasionally, so you can control how much cpu was used.
2. implement support for efficient updates of the easy cases (when a follow makes the graph bigger, or a path gets shorter)

Because option 1 broke the tests - that blocking should take effect immediately, I ended up going with the second option. This code regenerated the traversal only in the case of a block or a unfollow. After a while, though, the performance of _this_ became a problem. So I figured out how to dynamically update that too (turns out dynamic graph algorithms is a open research field, but I figured out a few tricks http://github.com/dominictarr/dynamic-dijkstra)

But this has caused the code to get quite complicated. maybe it's worth reconsidering 1?
The main problem, which maybe is something we can live with, or maybe we can work around it a way I hadn't thought of at the time, is that blocks on messages you replicate wouldn't take effect immediately.

On that note - you may get a similar effect when you resync. Maybe you block someone, then resync. it's possible that you get their messages faster than your own, so that you end up getting messages they wrote _after_ you blocked them. thought: maybe this is better handled in the UI layer, anyway?
Hmm, because you'll probably don't want to see their old messages either?

@ahdinosaur @mmckegg

**Comment by staltz** [comment]
I think `1` is a good idea, overall it would be better to have computation backpressure possibilities sprinkled around in the ssb ecosystem, so that apps can encode the prioritization logic (e.g. if an app wants to give very up-to-date info, then it would use less debouncing, if another app needs to prioritize early user experience, then more debouncing)

**Comment by dominictarr** [comment]
@mmckegg told me about a thing he and @pietgeursen was experimenting with in the rust stuff, where there is DB access (written in rust) embedded in the front end, and it gets called in `requestIdleCallback` (when the UI isn't doing anything) but then the rendering doesn't actually happen until `requestAnimationFrame` so this means the system stuff waits for the UI to be ready, so the UI is always smooth.

**Comment by dominictarr** [comment]
the problem with 1) is we'll need to rethink some big picture stuff. with 2) we can continue with the same basic architecture but need to get it working right.

**Comment by arj03** [comment]
Would it make sense to have performance numbers in the test, so you could see how much performance the complexity gains us in different "real-world" scenarios?

**Comment by dominictarr** [comment]
yes, that would actually make a lot of sense.
* brute force: regenerate entire graph at every new message
* incremental update: positive edges are updated efficiently (called an increment in the literature), falls back to regenerate on decrement.
* decremental update: negative edges (block, unfollow) are updated efficiently. (called decrement in the literature)
