### ISSUE TITLE
How do I do common queries?

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-friends#34]
Here are some queries I've struggled to be able to do : 
- **who follows my friend Laniyuk?**
  - this is currently hard to ask over RPC with the non-legacy api because `hopStream` is just looking at the graph from my position
- **who are the people I'm friends with**? (i.e. we follow one another)
  - I guess I could `hopStream` then hammer `isFollowing` 300 times? ):

There are other common queries but these seem like they need resolving first.

For reference, patchcore currently just uses the legacy API.

I'm still really excited about the potential of using a graph instead of boolean follow state ... it could unlock so much. I'm prepared to put energy into this to get it more use and support, but I think that only makes sense when you've got capacity @dominictarr

**Comment by dominictarr** [comment]
I agree stuff like this should be provided as an api, but thinking out loud how it might work
who are you friends with? the best way to calculate that would be to get the hops, up to ~1, and then check if they have a path back to you... easy way to check that is to calculate hops in reverse, then compare forward hops (follow paths away from you) with backward hops (follow paths to you). if `hops[x] == backward_hops[x]` then you are the same level friends with `x`

you can still get the graph - use `get` (oh just realized that wasn't documented... fixed that in my other pr)

**Comment by mixmix** [comment]
oh ... its seems like `hops` is a good method for things like determining who e.g. mikey's friends follows etc are ... I didn't realise that because it's half-documented. There's a hidden mode where you can use it like `hops(opts, cb)` which seems to do exactly what I want. D:
