### ISSUE TITLE
doc drive week 7: module triage

### ISSUE THREAD

**Issue by austinfrey** [ssbc/ssb-friends#35]
## rate the current state of the documentation out of 10.
7/10

## is it clear what this is used for? is anything confusing or weird?
yes, this seems very approachable to me.

## is there api documentation?
yes

## read code, do you see any undocumented methods?
no, all methods listed in the plugin manifest are documented

## for a method is there any undocumented options?
`hopStream` looks like it can take additional options. see [layered-graph#hopStream](https://github.com/ssbc/layered-graph/blob/master/index.js#L117)
`hops` can also accepts additional options. see [layered-graph#getHops](https://github.com/ssbc/layered-graph/blob/master/index.js#L92)

**Comment by mixmix** [comment]
agree it's important to know can call `sbot.friends.hops(opts, cb)`

opts seems to take : `{ start, reverse, max }`
