### ISSUE TITLE
legacy.stream() takes no arguments, but { live: true } passed

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-friends#41]
I saw that TypeScript supports plain old JS so I decided to give it a shot in a random repo. Look what I found!

https://github.com/ssbc/ssb-friends/blob/95a2bebb761ef899f66ecd272e646c3605f0e7f9/index.js#L81

@dominictarr  Was the intended behavior here important?

**Comment by dominictarr** [comment]
it seems that method is always `live` anyway https://github.com/ssbc/ssb-friends/blob/master/legacy.js#L88-L95

**Comment by mixmix** [comment]
yeah I noticed this as well Christian

**Comment by staltz** [comment]
No longer an issue because we removed that API
