### ISSUE TITLE
ssb-friends expects a replicate plugin to be available

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/ssb-friends#50]
In ssb-browser-demo, where ssb-friends is supposed to be disconnected from the replication functionality, I get this error:

https://github.com/ssbc/ssb-friends/blob/0ce97f890a254bb6b214e5ea3f2f79d73ef064fe/glue/replicate.js#L7

**Comment by arj03** [comment]
Not an error in this library. Was a in the browser code.
