### ISSUE TITLE
Spammed by news sources

### ISSUE THREAD

**Issue by sunjam** [ssbc/ssb-friends#54]
I've noticed that following basically any Pub inevitably leads me to being spammed by News sources being plugged into ssb via RSS.  Is there any better option for managing these beyond having to block each individually?  It is frustrating when you did not follow them to begin with.

**Comment by Powersource** [comment]
My personal recommendation is to not follow pubs (especially uncurated and public-invite pubs). You don't need to follow it to gossip with it or have it replicate your stuff.

As a more solid solution we should take a closer look at not replicating a feed if e.g. 1 of your friends follow a feed but 10 of your friends block it. But that'd be in another issue.

**Comment by sunjam** [comment]
What about those people who actually maintain the pub?  I suppose I could
create an all new identity, but that seems a step backwards.  Any
suggestions appreciated.
