### ISSUE TITLE
Eliminate flume

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/ssb-friends#56]
Would be nice if flumecodec and flumeview-reduce could be eliminated.  Right now, these are pulling in duplicate dependencies into ssb-browser-demo and increasing its size.

**Comment by KyleMaas** [comment]
As far as I can tell, this is the only thing that still uses flume:

https://github.com/ssbc/ssb-friends/blob/0ce97f890a254bb6b214e5ea3f2f79d73ef064fe/contacts.js

**Comment by arj03** [comment]
It will not be easy because they are used if you use this with db1. They code should be cleared out with some of the post processors, so I don't think this is a big problem.

**Comment by KyleMaas** [comment]
Okay.  I'll go ahead and close this, then.
