### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by cryptix** [ssbc/ssb-friends#6]
I fear ba7c55006c67e4ee1073e654a1467afd010ae222 introduced a crasher...

I can't start this new sbot i just installed, it seems to crash during updating the indexes:

```
...
******************************************........ (indexes:82.8%)
/home/cryptix/node_modules/ssb-friends/index.js:97
            push(k, patch[k][0])
                            ^

TypeError: Cannot read property '0' of null
    at /home/cryptix/node_modules/ssb-friends/index.js:97:29
    at /home/cryptix/node_modules/pull-flatmap/index.js:10:17
    at /home/cryptix/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/cryptix/node_modules/pull-stream/throughs/through.js:19:9
    at callback (/home/cryptix/node_modules/pull-pushable/index.js:85:5)
    at Function.push (/home/cryptix/node_modules/pull-pushable/index.js:44:7)
    at notify (/home/cryptix/node_modules/pull-notify/index.js:10:20)
    at /home/cryptix/node_modules/flumeview-reduce/inject.js:144:13
    at /home/cryptix/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/cryptix/node_modules/pull-cursor/cursor.js:32:13
```

I added this above the error
```
                if (patch[k] == null) {
                        console.dir(patch)
                        console.dir(v)
                        throw new Error("null patch?!")
                }
```

and it gives me the following values (not always these keys but always in that form...) but I'm not sure what to do with this...
```
{ '@YNnL5IkyOkZH7eLD7mPOsOx88tTbF6rh7/i9SB76Xkc=.ed25519': null }
{ from: '@7HHVZNWiNtCOquFNhNYS/DbHI9x3hFWrfxGP9FlJzHY=.ed25519',
  to: '@YNnL5IkyOkZH7eLD7mPOsOx88tTbF6rh7/i9SB76Xkc=.ed25519',
  value: true }

or 


{ '@ekg7cezI7BDglOJQVMVtr0a85Atf3BLusSLkXS4dZJc=.ed25519': null }
{ from: '@7HHVZNWiNtCOquFNhNYS/DbHI9x3hFWrfxGP9FlJzHY=.ed25519',
  to: '@ekg7cezI7BDglOJQVMVtr0a85Atf3BLusSLkXS4dZJc=.ed25519',
  value: true }

```

This started happening after creating a new key for a patchfoo installation. I invited it up to a pub which got me some messages, I then friend-ed it with my main key, making it replicate more messages leading to the crash.

**Comment by Happy0** [comment]
I'm also seeing this problem on the same line number.

**Comment by kewitz** [comment]
I'm having the same problem.

**Comment by dominictarr** [comment]
maybe but i'm having trouble figuring out what it is. I've made an update 2.3.3 can you try to upgrade to this, `rm ~/.ssb/flume/friends.json` restart sbot and see if that fixes it?

I think this is a problem with ordering... and it doesn't happen on my instance... can you provide me with your ~/.ssb/flume/log.offset file (zipped, it's fairly large) this doesn't have any private information and should allow me to debug it.

**Comment by kewitz** [comment]
So, is it possible that I fixed any corruption in my `friends.json` running that version with the commented conditional?
I'm being able to run normally right now, even without your new update.

**Comment by dominictarr** [comment]
sorry, make that ssb-friends@2.3.5

pretty sure I have figured this out.

Normally you replicate friends of friends, but not if you have blocked them. some times, someone is followed by one friend and blocked by another (in the code I call this a "frenemy" - both a friend of a friend and an enemy of a friend). In that case, you still replicate them, but you do not automatically replicate people that they follow.
But diffReachable wasn't handling that case, but I think it's fixed now.

@kewitz yes, if you got past that specific case by disabling diffReachable it won't need to process the messages that causes those bugs. But to be sure this is the correct fix, it's best if you regenerate `friends`, that way we'll be sure it's working.

**Comment by mmckegg** [comment]
We haven't heard from this bug for a while. Closing!
