### ISSUE TITLE
latest version is broke - no replication triggered

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-friends#68]
Rolled back to 4.2.1 to get replication working again

Looks like a nice refactor underway but worrying to see breaks in a minor release

**Comment by staltz** [comment]
Do you mean 4.4.7?

**Comment by staltz** [comment]
Also, could you try to do a git bisect to figure out which version broke things for you?

**Comment by mixmix** [comment]
Uhh, maybe yes. Might be better to write a test than do what I was doing
(writing a db analyzing bot and wondering why I had no data).

Wasn't to pair code in it sometime?

**Comment by mixmix** [comment]
Yes probably the latest tag. I installed fresh and immediately hit no
replication... Or actually maybe it was only replicating 1 hop when I asked
for 4.

**Comment by staltz** [comment]
> Wasn't to pair code in it sometime?

Happy to do that today (soonish) if you're up to it.

**Comment by mixmix** [comment]
For future reference, if you have a short time frame in mind, hit me up on
signal!
I have basically silent notifications for GitHub and barely check email

**Comment by staltz** [comment]
Could you try `ssb-replication-scheduler@1.0.0` and `ssb-ebt@7.0.0` and `ssb-friends@5.0.0`?

**Comment by mixmix** [comment]
Me?
Yes, would you like me to try it in patchbay?
Or Āhau? (a little nervous about that!)

Also, it's fine to run this with ***@***.*** yeah, and there are no ssb-db2
deps?

**Comment by staltz** [comment]
ssb-db2 not required. I recommend trying it in Āhau :) this needs to be production ready. At least I'm shipping it in Manyverse

**Comment by staltz** [comment]
This is an old enough issue, and ssb-friends not triggering replication is expected (new) behavior, so let's close this issue.
